# adapted from https://github.com/peaceiris/actions-gh-pages/blob/master/README.md#%EF%B8%8F-static-site-generators-with-nodejs and https://github.com/appleboy/scp-action/blob/master/README.md#example

name: deploy python basics

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: pull from github repo
      uses: appleboy/ssh-action@master
      with:
        host: ssh.pythonanywhere.com
        username: krother
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: cd academis/content/python_basics_DE && git pull
